Repository Samuelwanza/catalog-of-my-things, pull requests merged in 2023-09, with the labels that each got.

#32 Create Item Class - Group Task
  .github/workflows/linters.yml
  .rubocop.yml
  GemFile
  GemFile.lock
  MIT.md
  README.md
  classes/item.rb
Labels: Sana's Task

#33 Implement methods of Item Class - Group Task
  classes/item.rb
Labels: Sana's Task

#34 Create a main.rb file - Group Task
  main.rb
Labels: Sana's Task

#36 Create book and label classes
  classes/book.rb
  classes/item.rb
  classes/label.rb
Labels: Emmanule's Task

#37 Methods of book- label
  classes/book.rb
  classes/item.rb
  classes/label.rb
Labels: Emmanule's Task

#38 Test methods books & label
  .github/workflows/tests.yml
  classes/book.rb
  spec/book_spec.rb
  spec/label_spec.rb
Labels: Emmanule's Task

#39 Option book label
  app.rb
  classes/label.rb
  spec/label_spec.rb
Labels: Emmanule's Task

#40 Preserve data book & label
  app.rb
  book_data/books.json
  book_data/labels.json
  classes/book_info.rb
  classes/label.rb
  spec/label_spec.rb
Labels: Emmanule's Task

#42 Create a Game & Atuhor Class
  classes/author.rb
  classes/game.rb
Labels: Sana's Task

#43 Implement methods for Game & Author
  classes/author.rb
  classes/game.rb
Labels: Sana's Task

#44 Add unit tests for all methods of Game & Author
  classes/author.rb
  spec/author_spec.rb
  spec/game_spec.rb
Labels: Sana's Task

#45 Add options to Game & Author
  app.rb
  main.rb
Labels: Sana's Task

#46 Preserve data of Game & Author
  app.rb
  data/author.json
  data/books.json
  data/game.json
  data/labels.json
  main.rb
Labels: Sana's Task

#47 Book label changes
  app.rb
  classes/book_info.rb
  data/books.json
  data/labels.json
  database/schema.sql
  main.rb
Labels: Emmanule's Task

#48 Create a schema.sql file for Game & Author
  database/schema.sql
Labels: Sana's Task

#49 added genre and musicalbum setup
  classes/genre.rb
  classes/musicalbum.rb
  data/books.json
  data/labels.json
Labels: Samuel's Task

#51 Genre album options
  app.rb
  classes/musicalbum.rb
  main.rb
Labels: Samuel's Task

#52 preserved genre and album data in json files
  app.rb
  data/genre.json
  data/musicalbum.json
  module/datastore.rb
Labels: Samuel's Task

#54 added genre and album schema
  database/schema.sql
Labels: Samuel's Task
